-- H2 test catalog rebuild (mirrors prod V10).

ALTER TABLE IF EXISTS cof_deck RENAME TO old_cof_deck;
ALTER TABLE IF EXISTS cof_deck_pmv RENAME TO old_cof_deck_pmv;
ALTER TABLE IF EXISTS cof_card RENAME TO old_cof_card;

CREATE TABLE cof_deck (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    VARCHAR(255) NOT NULL,
    description             CLOB,
    back_url                VARCHAR(512) NOT NULL DEFAULT '',
    enabled                 BOOLEAN NOT NULL DEFAULT TRUE,
    review_status           VARCHAR(16) NOT NULL DEFAULT 'pending',
    pending_review_status   VARCHAR(16),
    pending_name            VARCHAR(255),
    pending_description     CLOB,
    pending_back_url        VARCHAR(512),
    submitter_client_id     VARCHAR(64),
    created_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at              TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_cof_deck_name ON cof_deck (name);

CREATE TABLE cof_pmv (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    VARCHAR(512) NOT NULL,
    author                  VARCHAR(255),
    description             CLOB,
    link                    VARCHAR(512),
    review_status           VARCHAR(16) NOT NULL DEFAULT 'pending',
    pending_review_status   VARCHAR(16),
    pending_name            VARCHAR(512),
    pending_author          VARCHAR(255),
    pending_description     CLOB,
    pending_link            VARCHAR(512),
    submitter_client_id     VARCHAR(64),
    created_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at              TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_cof_pmv_name ON cof_pmv (name);

CREATE TABLE cof_card (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deck_id                 BIGINT NOT NULL,
    pmv_id                  BIGINT NOT NULL,
    name                    VARCHAR(512),
    description             CLOB,
    image_url               VARCHAR(512) NOT NULL,
    review_status           VARCHAR(16) NOT NULL DEFAULT 'pending',
    pending_review_status   VARCHAR(16),
    pending_name            VARCHAR(512),
    pending_description     CLOB,
    pending_image_url       VARCHAR(512),
    submitter_client_id     VARCHAR(64),
    created_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at              TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_cof_card_image_url ON cof_card (image_url);
CREATE INDEX IF NOT EXISTS idx_cof_card_deck ON cof_card (deck_id);
CREATE INDEX IF NOT EXISTS idx_cof_card_pmv ON cof_card (pmv_id);
CREATE INDEX IF NOT EXISTS idx_cof_card_deck_pmv ON cof_card (deck_id, pmv_id);
