CREATE TABLE IF NOT EXISTS cof_deck (
    deck_id         VARCHAR(255) PRIMARY KEY,
    folder_name     VARCHAR(255) NOT NULL,
    name            VARCHAR(255) NOT NULL,
    curator         VARCHAR(255),
    description     CLOB,
    version         VARCHAR(64),
    link            VARCHAR(512),
    back_url        VARCHAR(512) NOT NULL,
    card_count      INTEGER NOT NULL DEFAULT 0,
    pmv_count       INTEGER NOT NULL DEFAULT 0,
    enabled         BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at      BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS cof_deck_pmv (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deck_id         VARCHAR(255) NOT NULL,
    pmv_id          INTEGER NOT NULL,
    name            VARCHAR(512) NOT NULL,
    author          VARCHAR(255),
    description     CLOB,
    link            VARCHAR(512),
    CONSTRAINT uk_cof_deck_pmv UNIQUE (deck_id, pmv_id)
);

CREATE INDEX IF NOT EXISTS idx_cof_deck_pmv_deck ON cof_deck_pmv (deck_id, pmv_id);

CREATE TABLE IF NOT EXISTS cof_card (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deck_id         VARCHAR(255) NOT NULL,
    pmv_id          INTEGER NOT NULL,
    card_id         VARCHAR(32) NOT NULL,
    shot            VARCHAR(8) NOT NULL,
    file_name       VARCHAR(255),
    image_url       VARCHAR(512) NOT NULL,
    card_uid        VARCHAR(512) NOT NULL,
    CONSTRAINT uk_cof_card UNIQUE (deck_id, pmv_id, card_id)
);

CREATE INDEX IF NOT EXISTS idx_cof_card_deck ON cof_card (deck_id);
