ALTER TABLE cof_deck_pmv DROP CONSTRAINT IF EXISTS uk_cof_deck_pmv;
ALTER TABLE cof_card DROP CONSTRAINT IF EXISTS uk_cof_card;
DROP INDEX IF EXISTS idx_cof_deck_pmv_deck;
DROP INDEX IF EXISTS idx_cof_card_deck;

ALTER TABLE cof_deck ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;
UPDATE cof_deck SET folder_name = deck_id WHERE folder_name IS NULL OR folder_name = '';
ALTER TABLE cof_deck ADD CONSTRAINT IF NOT EXISTS uk_cof_deck_folder UNIQUE (folder_name);

ALTER TABLE cof_deck_pmv ADD COLUMN IF NOT EXISTS deck_ref BIGINT;
UPDATE cof_deck_pmv SET deck_ref = (SELECT id FROM cof_deck WHERE cof_deck.deck_id = cof_deck_pmv.deck_id);
ALTER TABLE cof_deck_pmv DROP COLUMN deck_id;
ALTER TABLE cof_deck_pmv RENAME COLUMN deck_ref TO deck_id;

ALTER TABLE cof_card ADD COLUMN IF NOT EXISTS deck_ref BIGINT;
UPDATE cof_card SET deck_ref = (SELECT id FROM cof_deck WHERE cof_deck.deck_id = cof_card.deck_id);
ALTER TABLE cof_card DROP COLUMN deck_id;
ALTER TABLE cof_card RENAME COLUMN deck_ref TO deck_id;

ALTER TABLE cof_deck DROP PRIMARY KEY;
ALTER TABLE cof_deck DROP COLUMN deck_id;
ALTER TABLE cof_deck ADD PRIMARY KEY (id);

ALTER TABLE cof_deck_pmv ADD CONSTRAINT uk_cof_deck_pmv UNIQUE (deck_id, pmv_id);
ALTER TABLE cof_card ADD CONSTRAINT uk_cof_card UNIQUE (deck_id, pmv_id, card_id);
